// Code generated by MockGen. DO NOT EDIT.
// Source: models/apiModels/storage.go

// Package mock_apimodels is a generated GoMock package.
package mock_apimodels

import (
	reflect "reflect"

	dbmodels "github.com/CardozoCasariegoLuciano/StudyNotes-backend/models/dbModels"
	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockIstorage is a mock of Istorage interface.
type MockIstorage struct {
	ctrl     *gomock.Controller
	recorder *MockIstorageMockRecorder
}

// MockIstorageMockRecorder is the mock recorder for MockIstorage.
type MockIstorageMockRecorder struct {
	mock *MockIstorage
}

// NewMockIstorage creates a new mock instance.
func NewMockIstorage(ctrl *gomock.Controller) *MockIstorage {
	mock := &MockIstorage{ctrl: ctrl}
	mock.recorder = &MockIstorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIstorage) EXPECT() *MockIstorageMockRecorder {
	return m.recorder
}

// ComparePasswords mocks base method.
func (m *MockIstorage) ComparePasswords(hashedPass, bodyPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComparePasswords", hashedPass, bodyPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// ComparePasswords indicates an expected call of ComparePasswords.
func (mr *MockIstorageMockRecorder) ComparePasswords(hashedPass, bodyPass interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComparePasswords", reflect.TypeOf((*MockIstorage)(nil).ComparePasswords), hashedPass, bodyPass)
}

// DeleteNoteByID mocks base method.
func (m *MockIstorage) DeleteNoteByID(noteID int, model *dbmodels.Note) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNoteByID", noteID, model)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DeleteNoteByID indicates an expected call of DeleteNoteByID.
func (mr *MockIstorageMockRecorder) DeleteNoteByID(noteID, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNoteByID", reflect.TypeOf((*MockIstorage)(nil).DeleteNoteByID), noteID, model)
}

// FindUserByEmail mocks base method.
func (m *MockIstorage) FindUserByEmail(email string, model *dbmodels.User) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", email, model)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockIstorageMockRecorder) FindUserByEmail(email, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockIstorage)(nil).FindUserByEmail), email, model)
}

// GetAllNotes mocks base method.
func (m *MockIstorage) GetAllNotes(userID int, model *dbmodels.Notes) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotes", userID, model)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// GetAllNotes indicates an expected call of GetAllNotes.
func (mr *MockIstorageMockRecorder) GetAllNotes(userID, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotes", reflect.TypeOf((*MockIstorage)(nil).GetAllNotes), userID, model)
}

// GetNoteByID mocks base method.
func (m *MockIstorage) GetNoteByID(noteID int, model *dbmodels.Note) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteByID", noteID, model)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// GetNoteByID indicates an expected call of GetNoteByID.
func (mr *MockIstorageMockRecorder) GetNoteByID(noteID, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteByID", reflect.TypeOf((*MockIstorage)(nil).GetNoteByID), noteID, model)
}

// Save mocks base method.
func (m *MockIstorage) Save(anyModel interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", anyModel)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIstorageMockRecorder) Save(anyModel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIstorage)(nil).Save), anyModel)
}
