name: Deploy pipeline

on:
  push:
    branches: [master, develop]
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Install dependencies
        run: |
          go mod download

      - name: Build
        run: go run main.go

      - name: Test
        run: |
          go test -v ./...

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
